---
generator: hugo
version: 0.24.1
upload_path: "/static/assets/images"
frontmatter_file_url_template: "/docs/assets/images"
body_file_url_template: "/docs/assets/images"
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
